const $=s=>document.querySelector(s);
let session=null,games=[],filter='turn',busy=false;
async function api(action,body){const headers={};if(body!==undefined)headers['Content-Type']='application/json';if(session?.csrf)headers['X-FC-CSRF']=session.csrf;let response;try{response=await fetch('api/awbw/account?action='+action,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:JSON.stringify(body),credentials:'same-origin',cache:'no-store'});}catch{throw new Error('Could not connect. Check your connection and try again.');}let data;try{data=await response.json();}catch{throw new Error('Sign-in is being prepared. Please try again shortly.');}if(!response.ok){if(response.status===401&&action!=='login'){session=null;showSignIn();}throw new Error(data.message||'AWBW could not complete this request.');}return data;}
function showSignIn(){session=null;games=[];$('#signin-view').hidden=false;$('#games-view').hidden=true;$('#password').value='';$('#password').type='password';$('#show-password').textContent='SHOW';$('#show-password').setAttribute('aria-pressed','false');$('#show-password').setAttribute('aria-label','Show password');$('#signin').disabled=false;$('#signin-status').textContent='Sign in when you’re ready.';}
function renderGames(){const list=$('#games');list.replaceChildren();$('#turn-count').textContent=games.filter(g=>g.yourTurn).length;$('#game-count').textContent=games.length;const visible=games.filter(g=>filter==='all'||g.yourTurn);for(const game of visible){const link=document.createElement('a');link.className='game-card';link.href=`/play.html?game=${encodeURIComponent(game.id)}`;const badge=document.createElement('span');badge.className='turn-badge';badge.textContent=game.yourTurn?'YOUR TURN':'WAITING';const title=document.createElement('h2');title.textContent=game.title;const detail=document.createElement('p');detail.textContent=`AWBW #${game.id} · Open battlefield →`;link.append(badge,title,detail);list.append(link);}if(!visible.length){const p=document.createElement('p');p.className='empty-games';p.textContent=filter==='turn'?'No turns waiting. Your army can rest.':'No active games found in your AWBW list.';list.append(p);}}
async function loadGames(){if(busy)return;busy=true;$('#refresh').disabled=true;$('#games-status').textContent='Loading your AWBW games…';try{const data=await api('games');games=data.games;renderGames();$('#games-status').textContent=`${games.length} active game${games.length===1?'':'s'} · Updated just now`;}catch(error){$('#games-status').textContent=error.message;if(!session)$('#signin-status').textContent=error.message;}finally{busy=false;$('#refresh').disabled=false;}}
function showLobby(data){session=data;$('#signin-view').hidden=true;$('#games-view').hidden=false;$('#account-name').textContent=data.username;$('#password').value='';loadGames();}
$('#signin-form').onsubmit=async event=>{event.preventDefault();if(busy)return;busy=true;let signedIn=null;$('#signin').disabled=true;$('#signin-status').textContent='Signing in to AWBW…';try{signedIn=await api('login',{username:$('#username').value,password:$('#password').value});}catch(error){$('#signin-status').textContent=error.message;$('#password').value='';$('#password').focus();}finally{busy=false;$('#signin').disabled=false;}if(signedIn)showLobby(signedIn);};
$('#show-password').onclick=()=>{const show=$('#password').type==='password';$('#password').type=show?'text':'password';$('#show-password').textContent=show?'HIDE':'SHOW';$('#show-password').setAttribute('aria-label',show?'Hide password':'Show password');$('#show-password').setAttribute('aria-pressed',String(show));};
$('#signout').onclick=async()=>{if(busy)return;busy=true;$('#signout').disabled=true;try{await api('logout',{});showSignIn();}catch(error){$('#games-status').textContent=error.message;}finally{busy=false;$('#signout').disabled=false;}};
$('#refresh').onclick=loadGames;for(const button of document.querySelectorAll('[data-filter]'))button.onclick=()=>{filter=button.dataset.filter;for(const tab of document.querySelectorAll('[data-filter]'))tab.setAttribute('aria-selected',String(tab===button));renderGames();};
$('#signin').disabled=true;(async()=>{try{const data=await api('session');if(data.authenticated)showLobby(data);else showSignIn();}catch(error){$('#signin-status').textContent=error.message;$('#signin').disabled=true;}})();
